- name: Playbook para transferir arquivos
  hosts: all
  tasks:
  - name: Atualizar o arquivo resolv.conf
    become: true
    copy:
      src: resolv.conf
      dest: /etc/resolv.conf

# ansible-playbook copy.yaml

# ansible all -m shell -a "cat /etc/resolv.conf"